### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by kehlward79** [vrondakis/DarkRP-Leveling-System#12]
I recently added the DarkRP-Leveling-System to my Gmod DarkRP server (Im paying) and I was wondering if you could help me with the Purple and Black XP Bar, at the top of the screen!

Here is the image: http://steamcommunity.com/sharedfiles/filedetails/?id=372990856

Please help me, if you can!

**Comment by vrondakis** [comment]
You either don't have the material installed or don't have it on your fastdl. 


This is an issue that is specific to you, and is happening because you haven't installed the system correctly. Do not post about it.
