### ISSUE TITLE
Couldn't include file 'config.lua' (File not found) 

### ISSUE THREAD

**Issue by UnderYouFive** [vrondakis/DarkRP-Leveling-System#14]
I have the lastest version. But for some reason I get these errors.

Couldn't include file 'config.lua' (File not found) (@addons/darkrpmodification/lua/darkrp_modules/levels/sh_custom.lua (line 42))
Couldn't include file 'books.lua' (File not found) (@addons/darkrpmodification/lua/darkrp_modules/levels/sh_custom.lua (line 48))
Couldn't include file 'printers.lua' (File not found) (@addons/darkrpmodification/lua/darkrp_modules/levels/sh_custom.lua (line 49))

**Comment by vrondakis** [comment]
Cannot replicate your issue. Delete everything and try to re-install.
