### ISSUE TITLE
Printer Spawning Crashes Server

### ISSUE THREAD

**Issue by SubjectAlpha** [vrondakis/DarkRP-Leveling-System#16]
When I spawn any type of printer it crashes the server, it gives no lua error. I've been trying to fix it for a couple hours, but I can't find the issue.I'm using the most updated version of this module.

**Comment by vrondakis** [comment]
It's an issue with Garry's Mod and network vars caused by the latest
update.

Can't do anything until a hotfix is released.

**Comment by SubjectAlpha** [comment]
Alright, thank you for your assistance.
