### ISSUE TITLE
Changing so everyone gets EXP for a kill

### ISSUE THREAD

**Issue by SubjectAlpha** [vrondakis/DarkRP-Leveling-System#17]
I was trying to modify it so you get a set amount of EXP per human kill. I was editing in sv_addways.lua I tried to set the amount of EXP per kill to 1000, and make it so every level gets EXP if they make a kill.

http://pastebin.com/vgMkvUwz

My example.

**Comment by vrondakis** [comment]
So what? How is this an issue with the script?

**Comment by SubjectAlpha** [comment]
Its not, I was asking for some help. My apologies if I inconvenienced you.

**Comment by vrondakis** [comment]
You could just set .Friendly to false..
