### ISSUE TITLE
Error Help Please Spaming consle every time i give levels or some one levels up

### ISSUE THREAD

**Issue by BasonTaylor** [vrondakis/DarkRP-Leveling-System#18]
[ERROR] addons/ulx/lua/ulx/modules/sh/levels.lua:34: attempt to concatenate local 'calling_ply' (a userdata value)
  1. call - addons/ulx/lua/ulx/modules/sh/levels.lua:34
   2. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
    3. unknown - addons/ulib/lua/ulib/shared/commands.lua:1296
     4. Run - lua/includes/modules/concommand.lua:54
      5. unknown - addons/ulib/lua/ulib/shared/commands.lua:1310
       6. unknown - lua/includes/modules/concommand.lua:54

**Comment by BasonTaylor** [comment]
also it seems to be doing this to my scoreboard http://gyazo.com/6c284c841bfd33392e94e6e979ce56e6
and creating this error 
[ERROR] lua/includes/extensions/table.lua:414: invalid order function for sorting
  1. sort - [C]:-1
   2. SortByMember - lua/includes/extensions/table.lua:414
    3. populate - addons/bleur_scoreboard/lua/autorun/bleur_scoreboard.lua:339
     4. fn - addons/bleur_scoreboard/lua/autorun/bleur_scoreboard.lua:429
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

**Comment by Pooperscooper99** [comment]
What is the command to give levels?

**Comment by vrondakis** [comment]
Why would you ask that here?
