### ISSUE TITLE
There must be some other entity that has the value 'buyvrondakisregularprinterprinter' for 'cmd'.

### ISSUE THREAD

**Issue by mrprimeminister420** [vrondakis/DarkRP-Leveling-System#20]
I do not mean to bother but i am sure that this new update does not solve this issue. i have re installed the add-on multiple times and i still run into this error please get back to me as soon as possible. here is the whole error

There is 1 Lua problem!
	Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/darkrpmodification/lua/darkrp_modules/levels/sh_config.lua" on line 170.
The best help I can give you is this:

Corrupt entity: Regular Printer!
This entity does not have a unique value for 'cmd'.

Hints:
	- There must be some other entity that has the value 'buyvrondakisregularprinterprinter' for 'cmd'.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification/lua/darkrp_modules/levels/sh_config.lua on line 170
	2. addons/ulib/lua/ulib/shared/hook.lua on line 184
	3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 141
	4. addons/ulib/lua/ulib/shared/hook.lua on line 184
	5. gamemodes/darkrp/gamemode/init.lua on line 81
------- End of Simplerr error -------

**Comment by mrprimeminister420** [comment]
Also On the printers for the type of the printer all it says is "unknown"
Then Right under that it says the name of the owner of the printer
Then $0


Please respond as soon as possible i will be patient

**Comment by schiaffino** [comment]
Corrupt entity: Regular Printer!
This entity does not have a unique value for 'cmd'., 

Check your entities dude, you might have 2 entities with the same cmd = "regularprinter" or w/e.

**Comment by mrprimeminister420** [comment]
no i don't i have checked . or attempted to look their is only one regular printer entity  . but if i take out the regular printer it just says the same thing but with the golden printer.

**Comment by mrprimeminister420** [comment]
i understand what the problem is i just don't know why it gives me that error

**Comment by mrprimeminister420** [comment]
nor do i know how to solve it

**Comment by vrondakis** [comment]
Do you have the system installed twice or something?

**Comment by mrprimeminister420** [comment]
i actually might have it installed twice because i had a error beor but i solved it when i put the new updated version in

**Comment by mrprimeminister420** [comment]
could it be because i just put the new version that was updated 14 days ago Over the older version
....should i try to remove the whole thing and add it once more?

**Comment by vrondakis** [comment]
Definitely the issue

Good job

**Comment by mrprimeminister420** [comment]
ok so i wll remove every thing that the addon had from my server and i will re add it instead of just putting it over the old version illl do that now

**Comment by mrprimeminister420** [comment]
The errors are gone thank-you for support on the but now the printers are still slightly broken.. everything works they make the money but the display just says

                                                                   unknown
                                                                Owners name
                                                                        0$

And even when the printer sparks i can press e on it and get the money but the display never changes for any of the printers. it just stays the same  

                                                                   unknown
                                                                Owners name
                                                                        0$

Can i have support for this issue also?

**Comment by vrondakis** [comment]
Did you also remove the printer entity?

**Comment by mrprimeminister420** [comment]
yea i did.

**Comment by mrprimeminister420** [comment]
the printers work but the display on them is broken

**Comment by mrprimeminister420** [comment]
can we solve the printer issue?

**Comment by vrondakis** [comment]
Cannot replicate
