### ISSUE TITLE
Can't change NPC xp values

### ISSUE THREAD

**Issue by Pooperscooper99** [vrondakis/DarkRP-Leveling-System#22]
So I was trying to change the xp amounts for killing NPCs, could anyone help me? I went into sh_config and made the XP to 500, instead of 10, aaaand nothing changed

**Comment by vrondakis** [comment]
Dedinately your fault.

**Comment by Pooperscooper99** [comment]
... it isnt my fault your addon isnt working

**Comment by vrondakis** [comment]
The amount of XP given is determined by the 'LevelSystemConfiguration.NPCXPAmount' variable that is ONLY set in sh_config.lua

(That means it's your fault, you're not saving the file correctly or have the variable somewhere else. Not my problem)
